# Site
name: "Shuffle"
title: "Shuffle"
description: "Elite. Creative. Versatile."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
google_analytics: 'UA-137564287-2'
include: ["_pages"]
permalink: /:categories/:title/

# Authors
authors:
  shuffle:
    name: Shuffle
    display_name: Shuffle
    avatar: 'assets/images/logo.jpg'
    web: https://shuffle.github.io
    twitter: https://twitter.com/ShuffleTea38197
    # description: "Cybersecurity start-up focused on innovative R&amp;D. We love tackling challenges that are said to be impossible to solve!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
